service: serverless-lambda-pdflib
frameworkVersion: "1.64.0"

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  profile: hotpuma
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
        - arn:aws:s3:::pdflib-bucket/*
  s3:
    demoBucket:
      name: pdflib-bucket
      bucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      versioningConfiguration:
        Status: Suspended
plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

layers:
  Pdflib:
    name: Pdflib
    compatibleRuntimes:
      - nodejs12.x
    description: Required for Pdflib
    package:
      artifact: layer/pdflib-layer.zip
custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - pdf-lib
        - aws-sdk
    packager: "yarn"

  serverless-offline:
    location: .webpack/service

  customDomain:
    domainName: labs.mianio.com
    basePath: pdflib
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  pdflib-demo-s3:
    handler: functions/s3-demo.generate
    layers:
      - { Ref: PdflibLambdaLayer }
    events:
      - s3:
          bucket: demoBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .pdf

  pdflib-demo-http:
    handler: functions/http-demo.generate
    layers:
      - { Ref: PdflibLambdaLayer }
    events:
      - http:
          path: demo
          method: get
          cors: true
